#cloud-config
package_update: true
packages:
  - python3
  - python3-pip
  - git
  - nodejs
  - npm

runcmd:
  - git clone https://github.com/your-username/cyber-awareness-platform.git /opt/cyber-awareness
  - cd /opt/cyber-awareness/backend
  - pip3 install -r requirements.txt
  - nohup python3 app.py &